// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://salosgqtmyqoebigcshj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbG9zZ3F0bXlxb2ViaWdjc2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzc0OTUsImV4cCI6MjA2NDk1MzQ5NX0.yNsWwmxHC6Cc91EXm9oC9CBQvOcNVSPbjIw699Dn9gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);